import {expect, test} from "bun:test"

test("uses no visible imperative element construction or global Markdown CSS", async () => {
  const source = await Bun.file(new URL("../src/markdown.ts", import.meta.url)).text()
  const view = await Bun.file(new URL("../src/markdown-view.tsx", import.meta.url)).text()
  const action = await Bun.file(new URL("../src/components/overview-action-button.tsx", import.meta.url)).text()
  expect(source).not.toContain("createElement(")
  expect(source).not.toContain("storybookMarkdownCss")
  expect(view).toContain('from "@immersive/markdown"')
  expect(source).not.toContain("parseInline")
  expect(view).not.toContain("function MarkdownBlock")
  expect(view).toContain('from "./components/overview-action-button.tsx"')
  expect(view).not.toContain("codeEditorStyle")
  expect(view).not.toContain("actionStyle")
  expect(view).not.toContain("<section data-markdown-block")
  expect(view).not.toContain("<section data-markdown-list")
  expect(action).toContain('from "@immersive-ui/component/button/button"')
  expect(action).toContain('size="large"')
  expect(action).toContain('data-storybook-overview-action=""')
  expect(action).toContain("display: flex;")
  expect(action).toContain("flex-direction: row;")
  expect(action.match(/<Button[\s\S]*?\/>/u)?.[0]).not.toContain("style=")
  expect(view).not.toContain("createElement(")
})
