/** Воспроизводит browser-safe validators из опубликованной native JSON schema ACP. */
import Ajv2020 from "ajv/dist/2020.js"
import standaloneCode from "ajv/dist/standalone/index.js"
import protocol from "@agentclientprotocol/sdk/schema/schema.json"
import {createHash} from "node:crypto"
import {readFile, writeFile} from "node:fs/promises"
import {createRequire} from "node:module"
import {format} from "prettier"

const require = createRequire(import.meta.url)
const schemaSource = await readFile(require.resolve("@agentclientprotocol/sdk/schema/schema.json"), "utf8")
const digest = createHash("sha256").update(schemaSource).digest("hex")
const ajv = new Ajv2020({strict: false, allErrors: false, validateFormats: false, inlineRefs: false, code: {source: true, esm: true}})
const schemaId = "urn:storybook:chat-history:acp"
ajv.addSchema(protocol, schemaId)
const generated = standaloneCode(ajv, {
  validateContent: `${schemaId}#/$defs/ContentBlock`,
  validateUpdate: `${schemaId}#/$defs/SessionUpdate`,
})
const source = await format(
  `// Generated by official Ajv standalone; formatted by Prettier semi:false.\n// Source: @agentclientprotocol/sdk/schema/schema.json\n// Source SHA256: ${digest}\n${generated}\n`,
  {parser: "babel", semi: false, singleQuote: false, trailingComma: "none", printWidth: 100},
)
const target = new URL("../src/acp-validators.js", import.meta.url)
if (process.argv.includes("--check")) {
  if (await readFile(target, "utf8") !== source) throw new Error("ACP validators устарели: выполните generate:validators у Chat History")
} else await writeFile(target, source)
