/** Описания существующих возможностей контроллера для обоих транспортов. */
export const descriptions = [
  {name: "storybook_ensure", title: "Запуск Storybook", description: "Запускает или использует действующий единый сервер Storybook и при необходимости атомарно подключает указанные корни.", annotations: {readOnlyHint: false, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_status", title: "Состояние Storybook", description: "Возвращает состояние сервера, реестра, сессий пакетов и при необходимости представлений, не запуская сервер.", annotations: {readOnlyHint: false, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_attach", title: "Подключение проекта к Storybook", description: "Добавляет пакет, проект или рабочее пространство в сохранённый каталог Storybook. Использует существующие записи и восстанавливает ранее удалённые ветви.", annotations: {readOnlyHint: false, destructiveHint: false}},
  {name: "storybook_detach", title: "Удаление из каталога Storybook", description: "Удаляет одну ветвь проекта, пакета или рабочего пространства из сохранённого каталога Storybook и закрывает её представления. Файлы репозитория сохраняются.", annotations: {readOnlyHint: false, destructiveHint: true}},
  {name: "storybook_search", title: "Поиск в Storybook", description: "Ищет в едином графе Storybook и возвращает ограниченную страницу результатов.", annotations: {readOnlyHint: true, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_open", title: "Открытие представления Storybook", description: "Открывает кандидата выбранного пакета в подходящей существующей или новой фоновой вкладке, сохраняя представления других пакетов.", annotations: {readOnlyHint: false, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_wait", title: "Ожидание состояния Storybook", description: "Ожидает указанного состояния ревизии пакета или представления по событиям.", annotations: {readOnlyHint: true, destructiveHint: false}},
  {name: "storybook_inspect", title: "Инспекция представления Storybook", description: "Возвращает состояние, диагностику, консоль, семантическое дерево, раскладку, Display или Canvas с ограничением объёма ответа.", annotations: {readOnlyHint: true, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_interact", title: "Взаимодействие со Storybook", description: "Выполняет ограниченное действие над семантической целью без координат, произвольного JavaScript и идентификаторов CDP.", annotations: {readOnlyHint: false, destructiveHint: false}},
  {name: "storybook_capture", title: "Снимок представления Storybook", description: "Создаёт PNG-снимок выбранной отрисованной области и возвращает изображение вместе с ограниченным ресурсом результата.", annotations: {readOnlyHint: true, destructiveHint: false}},
  {name: "storybook_check", title: "Проверка пакета Storybook", description: "Проверяет и собирает выбранный пакет, затем автоматически применяет успешный результат. Ошибка сохраняет рабочую версию. Ожидайте итог и наблюдайте прогресс через status; срока ожидания сборки нет.", annotations: {readOnlyHint: false, idempotentHint: true, destructiveHint: false}},
  {name: "storybook_close", title: "Закрытие представления Storybook", description: "Закрывает только одно представление пакета Storybook по его точному идентификатору.", annotations: {readOnlyHint: false, destructiveHint: true}},
  {name: "storybook_stop", title: "Остановка Storybook", description: "Явно останавливает только принадлежащий этому инструменту единый сервер Storybook. Требуется confirm=true.", annotations: {readOnlyHint: false, destructiveHint: true, idempotentHint: true}},
  {name: "storybook_rebuild_web", title: "Пересборка интерфейса Storybook", description: "Пересобирает только Web в готовой среде и автоматически публикует успешный результат для HMR. Ошибка сохраняет рабочую оболочку. Передаёт стадии до итогового ответа; срока ожидания сборки нет.", annotations: {readOnlyHint: false, destructiveHint: false}},
  {name: "storybook_read_resource", title: "Ресурс Storybook", description: "Читает штатный ресурс состояния, графа, пакета, представления или снимка по URI, возвращённому Storybook.", annotations: {readOnlyHint: true, destructiveHint: false}}
] as const
